# Developed by Eng Mouaz M AlShahmeh
name: snack_flutter_game
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  google_fonts: ^2.3.1
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
